// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olyodvnjpgyjyuvgonap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9seW9kdm5qcGd5anl1dmdvbmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyOTE1NDAsImV4cCI6MjA1MDg2NzU0MH0.DxM92BAy11K1BwtoOIG_izeMJHEGtwKH9u7HE6VylLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);